
# Loss Data and Insurance Activities {#ChapIntro}


***

PdfEval = `r PdfEval`

A `r Gloss('qualitative')`, or `r Gloss('categorical variable')` is one for which the measurement denotes membership in a set of groups, or categories.


***

*Chapter Preview*. This book introduces readers to methods of analyzing insurance data. Section \@ref(S:Intro) begins with a discussion of why the use of data is important in the insurance industry. Section \@ref(S:PredModApps) gives a general overview of the purposes of analyzing insurance data which is reinforced in the Section \@ref(S:LGPIF) case study. Naturally, there is a huge gap between the broad goals summarized in the overview and a case study application; this gap is covered through the methods and techniques of data analysis covered in the rest of the text.


## Data Driven Insurance Activities {#S:Intro}

***
In this section, you learn how to:

- Summarize the importance of insurance to consumers and the economy
- Describe the role that data plays in managing insurance activities
- Identify data generating events associated with the timeline of a typical insurance contract

***



```{r Tab11, echo=FALSE}
Insample <- read.csv("Data/PropertyFundInsample.csv", header=T, na.strings=c("."), stringsAsFactors=FALSE)
Insample2010 <- subset(Insample, Year==2010)
temp <- table(Insample2010$Freq)
TotFreq <- length(Insample2010$Freq) 
Freq <- temp[1:9]
NinePlusFreq <- TotFreq - sum(Freq)
Number <- 0:8
Claims <- Number * Freq
TotClaims <- sum(Insample2010$Freq)
NinePlusClaims <- TotClaims - sum(Claims)
ProportionRow <- round(c(Freq/TotFreq, NinePlusFreq/TotFreq, 1),digits = 3)
tableout <- rbind( c("Number", Number, "9 or more", "Sum"),
                   c("Policies", Freq, NinePlusFreq, TotFreq),
                   c("Claims", Claims, NinePlusClaims, TotClaims),
                   c("Proportion", ProportionRow))

colnames(tableout) <- NULL
TableGen1(TableData=tableout,
         TextTitle= '2010 Claims Frequency Distribution',
         Align='c', Digits=3, ColumnSpec=1:8,
         ColWidth = ColWidth10)
knitr::kable(tableout)

```

